plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ticketingsitedemo'
version = '0.0.1-SNAPSHOT'
description = 'Demo project Server for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}
dependencies {
    // Spring Boot 기본
    implementation 'org.springframework.boot:spring-boot-starter'

    // Spring Web
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // JPA (CRUD용)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // MyBatis
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'

    // MySQL 드라이버
    runtimeOnly 'com.mysql:mysql-connector-j'

    // Lombok
    compileOnly 'org.projectlombok:lombok'

    // ThymeLeaf
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // 테스트용
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
